version: "3"

services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:latest
    # Expose Jellyfin's web interface and streaming service
    ports:
      - "8096:8096"
    # Where Jellyfin stores its internal data (library db, user prefs)
    volumes:
      - /mnt/storage/jellyfin/config:/config
      - /mnt/storage/jellyfin/cache:/cache
      # The actual media library on the SSD
      - /mnt/storage/media:/media

    # Restart if Pi reboots
    restart: unless-stopped

